### ISSUE TITLE
Is this project still alive? Is it maintained somewhere else?

### ISSUE THREAD

**Issue by wumpz** [fuzziness/kabeja#4]

**Comment by fuzziness** [comment]
Sorry, no. is maintained no more. AFAIK there's no other active fork

**Comment by fuzziness** [comment]
not to my knowledge

**Comment by optyfr** [comment]
See https://github.com/kaffamobile/kabeja
But problem with forks, is that we can't create issues...

**Comment by wumpz** [comment]
Just clone local remove origin and push to your new repo, then it is no fork anymore.
